
CREATE DATABASE IF NOT EXISTS ThucTapDB CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ThucTapDB;

CREATE TABLE TaiKhoan (
    ID_TaiKhoan VARCHAR(5) PRIMARY KEY,
    TaiKhoan VARCHAR(20),
    MatKhau VARCHAR(16),
    VaiTro NVARCHAR(30),
    TrangThai TINYINT
);

CREATE TABLE CanBoKhoa (
    ID_TaiKhoan VARCHAR(5) PRIMARY KEY,
    Ten NVARCHAR(50),
    TrangThai TINYINT,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

CREATE TABLE GiaoVien (
    ID_TaiKhoan VARCHAR(5) PRIMARY KEY,
    Ten NVARCHAR(50),
    Sdt VARCHAR(12),
    Email VARCHAR(250),
    TrangThai TINYINT,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

CREATE TABLE DotThucTap (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenDot VARCHAR(50),
    Nam VARCHAR(5),
    Loai VARCHAR(25),
    Nganh TEXT,
    NguoiQuanLy VARCHAR(255),
    ThoiGianBatDau DATE,
    ThoiGianKetThuc DATE,
    TenNguoiMoDot VARCHAR(255),
    TrangThai TINYINT
);

CREATE TABLE SinhVien (
    ID_TaiKhoan VARCHAR(5) PRIMARY KEY,
    ID_Dot INT,
    Ten NVARCHAR(50),
    Lop NVARCHAR(50),
    Diem INT,
    XepLoai NVARCHAR(50),
    MSSV VARCHAR(12),
    ID_GVHD VARCHAR(5),
    TrangThai TINYINT,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan),
    FOREIGN KEY (ID_Dot) REFERENCES DotThucTap(ID),
    FOREIGN KEY (ID_GVHD) REFERENCES GiaoVien(ID_TaiKhoan)
);

CREATE TABLE TaiNguyenThucTap (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Ten VARCHAR(255),
    DuongDan VARCHAR(255),
    NguoiDang VARCHAR(255),
    TrangThai TINYINT
);

CREATE TABLE CongTy (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaSoThue VARCHAR(250),
    TenCty VARCHAR(250),
    LinhVuc VARCHAR(250),
    Sdt VARCHAR(50),
    Email VARCHAR(250),
    DiaChi TEXT,
    MoTa TEXT,
    TrangThai TINYINT
);

CREATE TABLE GiayGioiThieu (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenCty VARCHAR(250),
    MaSoThue VARCHAR(250),
    LinhVuc VARCHAR(250),
    Sdt VARCHAR(50),
    Email VARCHAR(250),
    DiaChi TEXT,
    MoTa TEXT,
    IdSinhVien VARCHAR(5),
    TrangThai TINYINT,
    FOREIGN KEY (IdSinhVien) REFERENCES SinhVien(ID_TaiKhoan)
);

CREATE TABLE BaoCao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDSV VARCHAR(5),
    IdGVHD VARCHAR(5),
    Tuan VARCHAR(10),
    CongviecThucHien TEXT,
    DanhGia TEXT,
    TrangThai TINYINT,
    FOREIGN KEY (IDSV) REFERENCES SinhVien(ID_TaiKhoan),
    FOREIGN KEY (IdGVHD) REFERENCES GiaoVien(ID_TaiKhoan)
);

CREATE TABLE ThongBao (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TieuDe NVARCHAR(250),
    NoiDung TEXT,
    NgayDang DATETIME,
    ID_TaiKhoan VARCHAR(5),
    TrangThai TINYINT,
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);
CREATE TABLE TEPDINHKEM (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TENFILE VARCHAR(255),
    ID_THONGBAO INT,
    FOREIGN KEY (ID_THONGBAO) REFERENCES THONGBAO(ID)
);
CREATE TABLE KhaoSat (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TieuDe NVARCHAR(255),
    MoTa TEXT,
    NguoiTao VARCHAR(5),
    ThoiGianTao DATETIME,
    TrangThai TINYINT,
    FOREIGN KEY (NguoiTao) REFERENCES TaiKhoan(ID_TaiKhoan)
);

CREATE TABLE CauHoiKhaoSat (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_KhaoSat INT,
    NoiDung TEXT,
    LoaiCauHoi VARCHAR(20),
    TrangThai TINYINT,
    FOREIGN KEY (ID_KhaoSat) REFERENCES KhaoSat(ID)
);

CREATE TABLE PhanHoiKhaoSat (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_KhaoSat INT,
    ID_TaiKhoan VARCHAR(5),
    ThoiGianTraLoi DATETIME,
    TrangThai TINYINT,
    FOREIGN KEY (ID_KhaoSat) REFERENCES KhaoSat(ID),
    FOREIGN KEY (ID_TaiKhoan) REFERENCES TaiKhoan(ID_TaiKhoan)
);

CREATE TABLE CauTraLoi (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PhanHoi INT,
    ID_CauHoi INT,
    TraLoi TEXT,
    TrangThai TINYINT,
    FOREIGN KEY (ID_PhanHoi) REFERENCES PhanHoiKhaoSat(ID),
    FOREIGN KEY (ID_CauHoi) REFERENCES CauHoiKhaoSat(ID)
);

CREATE TABLE File (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenFile VARCHAR(30),
    File BLOB,
    ID_SV VARCHAR(5),
    ID_GVHD VARCHAR(5),
    TrangThai TINYINT,
    FOREIGN KEY (ID_SV) REFERENCES SinhVien(ID_TaiKhoan),
    FOREIGN KEY (ID_GVHD) REFERENCES GiaoVien(ID_TaiKhoan)
);

CREATE TABLE TongKet (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDSV VARCHAR(5),
    ID_GVHD VARCHAR(5),
    Diem FLOAT,
    DanhGia TEXT,
    TrangThai TINYINT,
    FOREIGN KEY (IDSV) REFERENCES SinhVien(ID_TaiKhoan),
    FOREIGN KEY (ID_GVHD) REFERENCES GiaoVien(ID_TaiKhoan)
);
